FileVersion = 1

[Project]
Name = "GLFW"
TargetType = "BeefLib"
StartupObject = "GLFW.Program"

[Configs.Debug.Win64]
OtherLinkFlags = "$(LinkFlags) gdi32.lib shell32.lib"
LibPaths = ["$(ProjectDir)/dist/windows/glfw3_mt.lib"]

[Configs.Release.Win64]
OtherLinkFlags = "$(LinkFlags) gdi32.lib shell32.lib"
LibPaths = ["$(ProjectDir)/dist/windows/glfw3_mt.lib"]

[Configs.Paranoid.Win64]
OtherLinkFlags = "$(LinkFlags) gdi32.lib shell32.lib"
LibPaths = ["$(ProjectDir)/dist/windows/glfw3_mt.lib"]

[Configs.Test.Win64]
OtherLinkFlags = "$(LinkFlags) gdi32.lib shell32.lib"
LibPaths = ["$(ProjectDir)/dist/windows/glfw3_mt.lib"]

[Configs.Debug.Linux64]
OtherLinkFlags = "$(LinkFlags) -lglfw"

[Configs.Release.Linux64]
OtherLinkFlags = "$(LinkFlags) -lglfw"

[Configs.Paranoid.Linux64]
OtherLinkFlags = "$(LinkFlags) -lglfw"

[Configs.Test.Linux64]
OtherLinkFlags = "$(LinkFlags) -lglfw"
