FileVersion = 1

[Project]
Name = "glfw-beef"
TargetType = "BeefLib"
StartupObject = "glfw-beef.Program"

[Configs.Debug.Win32]
LibPaths = ["$(ProjectDir)/dist/x86/glfw3dll.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/*.dll\")"]

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/x64/glfw3dll.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/*.dll\")"]

[Configs.Release.Win32]
LibPaths = ["$(ProjectDir)/dist/x86/glfw3dll.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/*.dll\")"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/x86/glfw3dll.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/*.dll\")"]
